export const XP_ANIMATION_DURATION = 4000;

export const CONFETTI_ANIMATION_DURATION = 3000;
export const CONFETTI_NUMBER = 40;

export const BACKTEST_ANIMATION_DURATION = 500;

export const PORTFOLIO_STARTING_VALUE = 10000;
